### ISSUE TITLE
No modal template selector on section with a content template defined

### ISSUE THREAD

**Issue by daltonrooney** [spicywebau/craft-content-templates#4]
### Bug Description

I've created a content template for my `pages` structure, but when I create a new entry, there's no modal template selector.

I noticed the modal does work on my `news` channel, is it possible that the template selector doesn't work on structure sections? Or another issue?

### Steps to reproduce

1. Create a new template for `pages` section
2. Create new entry in `pages` section
3. No modal template selector

### Content Templates version

1.0.2

### Craft CMS version

4.4.17

**Comment by daltonrooney** [comment]
A little bit more info on this issue, I believe this is caused by fields on the entry with default values. I dumped the value of `Collection::make($element->getFieldLayout()->getCustomFields())->filter(fn($field) => !$element->isFieldEmpty($field->handle))` and I got an array of radio and lightswitch fields with defaults already set. 

These defaults are a pretty important part of our page layouts, I'd prefer not to remove them. Can you think of a way to bypass default field values?

**Comment by daltonrooney** [comment]
Trying a few things here because I'd like to demo this for our client tomorrow. For our purposes we only need to show the modal when an entry is new, so I replaced the `isFieldEmpty()` conditional with a test for `$element->isFresh`

https://github.com/madebyraygun/craft-content-templates/commit/e8e7a47649b5716603e6644c6deecb672a9bd6f4

This solves the problem for us but I can understand if it's not the right solution for the plugin.

**Comment by ttempleton** [comment]
I admit that I did not think of this 😅

`$element->isFresh` is an improvement in that it makes the modal appear at all when creating a new entry, but it also makes the modal appear when reloading the draft, including when applying a content template. I wonder if there's a combination of settings we can use to guarantee that it's a brand new entry... I'll have a look into that.

**Comment by daltonrooney** [comment]
@ttempleton You’re right, the modal does continue to load even after selecting a template. Not a perfect solution. 😀 I worked around this temporarily with https://github.com/madebyraygun/craft-content-templates/commit/3518d2d71a525d3d5fccdb43be54526b5dc9e964 but I’m sure there’s a better solution.

**Comment by ttempleton** [comment]
Just released 1.0.3, which checks for an unpublished draft that hasn't had a slug set yet, and then shows the modal. This does mean that changes to fields/properties other than the slug can be made, and reloading the draft would still cause the modal to reappear – which is still a bug, but arguably a less serious one.

**Comment by daltonrooney** [comment]
Thanks, that sounds like a great solution, we'll give it a try.
