### ISSUE TITLE
Cannot create template

### ISSUE THREAD

**Issue by FlipLucky** [spicywebau/craft-content-templates#6]
### Bug Description

Hello, 
I am an avid Neo block user willing to add Content Templates to our toolbelt. 
Unfortunately, I am running into an issue that i cannot create a template, without too much details.

for comparison, this is a screenshot for when I forget to add a template titel: 
![image](https://github.com/spicywebau/craft-content-templates/assets/81532419/3e8bf626-ee05-41b4-82e9-39b64fe69c40)

Which gives me every leads I need
As soon as i fill out the title field, and press create again, i get this:

![image](https://github.com/spicywebau/craft-content-templates/assets/81532419/ac3dd17d-3968-4ca2-af6b-7a5373988085)

WIth a lead, i can probably troubleshoot most issues, but this doens't give me any lead at all unfortunately. 
Edit: A draft is created, but it cannot be saved as actual template
### Steps to reproduce

1.Add Trial to local environment
2.Open Plugin section from left navigation.
3.Select section 
4. Create new template
5. Add title
6. Try to save.

### Content Templates version

"1.0.5"

### Craft CMS version

"4.5"

**Comment by FlipLucky** [comment]
I am trying to exclude all possible things. 
The setup is running in docker, but dont get any feedback from the containers that something is not allowed. 
Since the draft is created, but not the actual template, i will also go and look through the database to see if the template cannot be stored for some reason

**Comment by ttempleton** [comment]
Are there any errors in your Craft logs involving this plugin?

Which field(s) are being used in the SEO tab? I'm wondering if there's an incompatibility issue, e.g. with another plugin-provided field type.

**Comment by FlipLucky** [comment]
I think your hunch is right
the craft log is quite extensive, and hard to skim through, but i did find this: 

2023-10-05 19:15:36 [web.INFO] [application] Unexpected data encountered in config data - ether\seo\models\data\SeoData Object

edit: when trying to save a template*

**Comment by FlipLucky** [comment]
Allright, i did a crossexamination. 
When i add the SEO field from Ether, i cannot save the template
When i remove the SEO field, i can save a template
It seems there is a conflict.

**Comment by ttempleton** [comment]
Thanks for confirming that, it should now be fixed in 1.0.6.
