### ISSUE TITLE
Error when applying project config

### ISSUE THREAD

**Issue by JeroenJRP** [spicywebau/craft-content-templates#8]
### Bug Description

When creating templates in our local environment and then trying to apply the updated project config in another environment I got the following error from the `craft project-config/apply` command.

```
Applying changes from your project config files ...
- updating dateModified ... done
- adding contentTemplates.templates.7e5e9da8-b094-4a0b-9017-fcf829c93e97.content.seo.metaContainers.MetaJsonLdContainergeneral ... 
  - adding contentTemplates.templates.7e5e9da8-b094-4a0b-9017-fcf829c93e97 ... 
error: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`foodcraft_db`.`contenttemplates`, CONSTRAINT `fk_qguthubmsicmrjgozhkauiabxskpbadibnub` FOREIGN KEY (`id`) REFERENCES `elements` (`id`) ON DELETE CASCADE)
The SQL being executed was: INSERT INTO `contenttemplates` (`typeId`, `previewImage`, `description`) VALUES (1, NULL, '')
```

### Steps to reproduce

1. Create Content Template in local environment
2. Upload files to other environment (with `allowAdminChanges` on `false`)
3. Apply project config changes on this environment

### Content Templates version

1.0.7

### Craft CMS version

4.9.6

**Comment by ttempleton** [comment]
Thanks for reporting that - fixed now in 1.0.8 and 2.0.1.
